#ifndef USER_MACROS_H
#define USER_MACROS_H
/*generated by SCADE Code Generator*/
//#include "libraries/SC65/libmathext/macro_libmathext64.h"
//#include "libraries/SC65/libmathext/macro_libmathext32.h"
#include "/cygdrive/C/Program Files (x86)/Esterel Technologies/SCADE R17.2/SCADE/libraries/libmathext/macro_libmathext.h"

#ifndef kcg_assume
#define kcg_assume(x)
#endif

#ifndef kcg_guarantee
#define kcg_guarantee(x)
#endif

#endif /*USER_MACROS_H*/
